Vagrant.configure("2") do |config|
  # Image de base pour toutes les machines
  config.vm.box = "ubuntu/jammy64"

  # --- VM1 : ROUTER ---
  config.vm.define "router" do |router|
    router.vm.hostname = "vm1-router"
    # Interface DMZ
    router.vm.network "private_network", ip: "192.168.100.1", virtualbox__intnet: "dmz-net"
    # Interface LAN
    router.vm.network "private_network", ip: "192.168.10.1", virtualbox__intnet: "lan-net"
    
    # On lance le script de configuration (iptables, ip_forward)
    router.vm.provision "shell", path: "scripts/setup-router.sh"
  end

  # --- VM2 : WEB ---
  config.vm.define "web" do |web|
    web.vm.hostname = "vm2-web"
    web.vm.network "private_network", ip: "192.168.100.10", virtualbox__intnet: "dmz-net"
    
    # On installe le serveur web et l'app
    web.vm.provision "shell", path: "scripts/setup-web.sh"
  end

  # --- VM3 : DB ---
  config.vm.define "db" do |db|
    db.vm.hostname = "vm3-db"
    db.vm.network "private_network", ip: "192.168.10.10", virtualbox__intnet: "lan-net"
    
    # On installe MySQL
    db.vm.provision "shell", path: "scripts/setup-db.sh"
  end

  # Optimisation des ressources
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024" # 1Go par machine suffit
    vb.gui = false     # Pas d'interface graphique pour gagner de la place
  end
end
